name: "coding standards"

on:
  pull_request: ~
  push: ~

jobs:
  coding-standards:
    name: "coding standards"
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"

      - name: "installing PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr
          extensions: bcmath, mbstring, intl, sodium, json

      - name: "installing dependencies"
        run: |
          make install-root-dependencies
          make install-coding-standard-dependencies

      - name: "checking coding standards"
        run: php tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --config=tools/php-cs-fixer/.php_cs.dist.php --dry-run --format=checkstyle | cs2pr