name: "static analysis"

on:
  pull_request: ~
  push: ~
  schedule:
    - cron: '0 */3 * * *'

jobs:
  static-analysis:
    name: "static analysis"
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"

      - name: "installing PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr
          extensions: bcmath, mbstring, intl, sodium, json

      - name: "installing dependencies"
        run: |
          make install-root-dependencies
          make install-static-analysis-dependencies
      - name: "running static analysis"
        run: php tools/psalm/vendor/bin/psalm -c tools/psalm/psalm.xml --show-info=true --no-cache --output-format=checkstyle | cs2pr

      - name: "calculating type coverage"
        run: make type-coverage